function SC = shcon(edge, X, Y, F)
%Usage:
%     SC = shape_context(edge, X, Y, F)
%
%Input:
% edge: the black wihite map generated by edge detection 
% X, Y: the coordinates of sample points in the binary map bw
% F : the context generating filters, (2r+1)-by-(2r+1)-by-(rb*tb) 3D matrix,
%     in which rb and tb are the number of radius bins and theta bins; r is
%     the largest radius of shape context descriptor
% 
%Output:
% SC: ns-by-(rb*tb) matrix of shape contexts of each sample

bw = zeros( size(edge));
bw( sub2ind( size(edge), Y, X)) = 1; % get sample points

r = (size(F, 1)-1)/2; % radius
nf = size(F, 3); % # of feature elements per descriptor
[m n] = size( bw );
ns = numel(Y);

BW = zeros( m + 2*r, n + 2*r ); 
BW( r+1 : r+m, r+1 : r+n) = bw(:,:);
% BW is bw padded r zeros along each edge
BW3d = repmat(BW, [1, 1, nf]); 
% BW3d is duplicated BW's by number of per-descriptor elements

rx2 = r * 2;
SC = zeros(ns, nf); % allocate memory for descriptors
for k = 1 : ns
    NB3d = BW3d( Y(k) : Y(k) + rx2, X(k): X(k) + rx2, :);
    % NB3d is the nighbor around edge point [Y(k), X(k), :] in BW3d
    sc = sum( sum( NB3d .* F, 1), 2);
    SC(k, :) = sc(:);
end

